name: OLD Build and push image

# on: 
#   workflow_dispatch:
#   push:
#     branches:
#       - "**"
#     tags:
#       - "v*.*.*"
#   pull_request:
#     branches:
#       - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
    -
      name: Build and push
      id: build_and_push
      run: |
        set -e
        # Build and push images
        yarn install
        npm install -g @devcontainers/cli
        devcontainer build --workspace-folder ./ --image-name ghcr.io/${GITHUB_REPOSITORY}:latest --push true