name: Build and push image

on: 
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
      run: |
        set -e
        # Build and push images
        yarn install
        npm install -g @devcontainers/cli
        devcontainer build 
                          --image-name ghcr.io/${GITHUB_REPOSITORY}:latest 
                          --push true
                          --workspace-folder /workspaces/node-bulletin-board
                          