name: Build and push image

on: 
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - 
      name: Build and push
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
      run: |
        set -e
        # Build and push images
        yarn install
        npm install -g @devcontainers/cli
        devcontainer build 
                          --image-name ghcr.com/${GITHUB_REPOSITORY}:latest 
                          --push true
                          --workspace-folder ../workspace